name: Test CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-cmake:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cmake
        run: brew install cmake

      - name: Build
        run: cmake -S . -B build && cmake --build build

  build-xcode:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cmake
        run: brew install cmake

      - name: Build
        run: |
          xcodebuild -project experiment.xcodeproj -scheme experiment -configuration Release build